// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.TravelPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TravelPlans");
                });

            modelBuilder.Entity("Domain.Entities.TravelPlan", b =>
                {
                    b.OwnsOne("Domain.Entities.Travel", "TravelHome", b1 =>
                        {
                            b1.Property<Guid>("TravelPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ArrivalDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ArrivalLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DepartureDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DepartureLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("TravelPlanId");

                            b1.ToTable("TravelPlans");

                            b1.WithOwner()
                                .HasForeignKey("TravelPlanId");
                        });

                    b.OwnsOne("Domain.Entities.Travel", "TravelTo", b1 =>
                        {
                            b1.Property<Guid>("TravelPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ArrivalDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ArrivalLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("DepartureDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("DepartureLocation")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("TravelPlanId");

                            b1.ToTable("TravelPlans");

                            b1.WithOwner()
                                .HasForeignKey("TravelPlanId");
                        });

                    b.Navigation("TravelHome")
                        .IsRequired();

                    b.Navigation("TravelTo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
